[project]
name = "git_stats"
version = "0.1.0"
description = "Analyse/Visualise git logs with Streamlit/Pandas"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.52.1",
    "pandas>=2.0.0",
]
